### ISSUE TITLE
Invalid domain: igrid.org^

### ISSUE THREAD

**Issue by p1r473** [bentasker/adblocklists#2]
Hi, you have an invalid domain entry: igrid.org^ in blocklist
Has an invalid character

**Comment by bentasker** [comment]
Hi, 

Sorry, missed the notification on this.

**Comment by bentasker** [comment]
Fixed in the codebase, but won't be in the lists yet as there's some other stuff I'm going to get done before deploying

**Comment by bentasker** [comment]
OK, this is live in the lists

    # grep igrid blockeddomains.txt 
    igrid.org

Though caches on the CDN may need to expire first.

**Comment by p1r473** [comment]
Thanks!
