### ISSUE TITLE
img1.wsimg.com

### ISSUE THREAD

**Issue by p1r473** [bentasker/adblocklists#3]
This domain is GoDaddy image hosting, for sites using GoDaddy
I believe this to be a flase positive
Thanks,
@bentasker

**Comment by bentasker** [comment]
Unfortunately it is (was?) used for other purposes too: https://github.com/bentasker/adblocklists/commit/423a33d467304589c5756e987add60d16d4d6fc7

It is a tricky one though - IIRC blocking this domain does also break their management console. I've a feeling I've seen reference to other stuff being served from there too, but can't find any links offhand.

**Comment by p1r473** [comment]
I was on a blog hosted on GoDaddy and the images were hosted on this domain
No problem I have whitelisted locally

**Comment by bentasker** [comment]
Thanks, I'll try and find time to have a poke about to see if they're still doing similar or if it really is just images now.

**Comment by bentasker** [comment]
For reference, it seems they are still doing it.

However, they continue to serve the underlying JS from the same subdirectory, so I've removed the domain wide block and just blocked that directory now (IIRC at the time I added the domain originally, I hadn't yet added the ability to block specific paths).

[ADBLK-28](https://projects.bentasker.co.uk/jira_projects/browse/ADBLK-28.html) refers
